// source https://www.cosmopolitan.com/uk/worklife/a32313763/truth-or-dare-questions/#best-truth-questions
export const data = {
  truth: [
    "Who's the last person you searched on Instagram?",
    "What's the strangest thing you've ever eaten?",
    "What's your relationship dealbreaker?",
    "What's a secret you've never told anyone?",
    "Do you have a hidden talent?",
    "Who was your first celebrity crush?",
    "Have you ever cheated in an exam?",
    "If you were going to be on a reality TV show, which would it be?",
    "What's your biggest insecurity?",
    "What's the biggest mistake you've ever made?",
    "What's one thing you hate people knowing about you?",
    "What's the worst thing anyone's ever done to you?",
    "What's the best thing anyone's ever done for you?",
    "What's your worst habit?",
    "What's the biggest misconception about you?",
    "What's one thing you wish people knew about you?",
    "Why did your last relationship break down?",
    "What's the best piece of advice you've been given?",
    "What's the most you've spent on a night out?",
    "Have you ever returned or re-gifted a present?",
    "Do you have a favourite sibling?",
    "What have you purchased that's been the biggest waste of money?",
    "How would you rate your looks on a scale of 1 to 10?",
    "What celebrity do you look up to?",
    "If you could be one celebrity for a day, who would it be?",
    "If you could do any job in the world, what would it be?",
    "What's your dream life?",
    "What do you value the most - money, fame, success, friends, family, etc?",
    "What’s your biggest red flag?",
    "What’s one movie you’re embarrassed to admit you enjoy?",
    "What music artist do you secretly think is overrated?",
    "What’s your most controversial political opinion?",
    "Name something you can’t live without",
    "Where do you think you’ll be in five years time?",
    "How well do you think you’d do in a horror movie?",
    "How many stuffed animals do you own?",
    "Did you ever get in trouble at school? And if so what for?",
    "Do you have any phobias?",
    "What's the drunkest you've ever been?",
    "What's the most embarrassing thing you've ever done?",
    "What's the most disgusting thing you've ever done?",
    "What's the most embarrassing thing you've done in a taxi?",
    "What's the silliest reason you've left a club early?",
    "Tell me about your first kiss",
    "What was the most inappropriate time you farted?",
    "What's something you really hope your family never finds out about?",
    "Who do you think is the worst-dressed person in this room?",
    "Have you ever practiced kissing in a mirror?",
    "What's your worst fashion moment?",
    "What's your biggest pet peeve?",
    "What TV character do you relate to the most?",
    "Have you ever dined and dashed?",
    "Have you ever had sex on the beach?",
    "Would you like to be a member of the mile-high club?",
    "Would you consider going on Love Island?",
    "What's the worst meal you've ever cooked?",
    "Have you ever done a strip tease for a partner?",
    "If you could pick one other player to take with you to a deserted island, who would it be?",
    "If you suddenly had a million pounds, how would you spend it?",
    "Who in the group would you want by your side in a zombie apocalypse?",
    "Which fashion trend are you embarrassed to admit you’ve taken part in?",
    "Have you ever had an imaginary friend?",
    "How often do you wash your sheets?",
    "Do you believe in aliens?",
    "What's the worst thing you've ever done at work?",
    "Do you have any fetishes?",
    "What's something you're glad your family doesn't know about you?",
    "Have you ever cheated on someone?",
    "What's the worst thing you've ever done?",
    "What are your thoughts on polyamory?",
    "What's the worst intimate experience you've ever had?",
    "What's the best intimate experience you've ever had?",
    "Have you ever broken the law?",
    "Have you ever stayed friends with someone because it benefitted you beyond just the friendship?",
    "Who would you like to kiss in this room?",
    "Have you ever had a run in with the law?",
    "What's the worst thing you've ever said to anyone?",
    "Have you ever been caught doing something you shouldn't have?",
    "What's the worst date you've been on?",
    "What's the best date you've been on?",
    "What happened on the latest night out you had?",
    "What's your biggest regret?",
    "Have you ever said something you regret about someone in this room?",
    "Have you ever lied to get out of a bad date?",
    "What's the most trouble you've been in?",
    "When did you last have sex outside?",
    "What's the worst thing you've lied about?",
    "What's one thing you wish you'd lied about?",
    "Name a time you think you were a bad partner",
    "If you had to cut one friend out of your life, who would it be?",
    "What's your guilty pleasure?",
    "If you had to get back with an ex, who would you choose?",
    "Do you have a favourite friend?",
    "What's your biggest turn on?",
    "If you could swap lives with someone in this room, who would it be?",
    "Have you ever told a lie about your BFF to make yourself look better?",
    "Have you ever had a holiday romance?",
    "Have you ever had a festival romance?",
    "What is something you would do if you knew there were no consequences?",
    "What’s your toxic trait?",
    "Do you still have feelings for any of your exes?",
    "What’s more important you - love or money?",
    "Who do you think should pay on a first date?",
    "What nickname do you call your partner/ they call you?",
  ],
  dare: [
    "Try to juggle 3 things of the group's choice",
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Do 100 squats",
    "Let the group look in your Instagram DMs",
    "Show us your screen time report",
    "Keep three ice cubes in your mouth until they melt",
    "Yell out the first word that comes to your mind",
    "Keep your eyes closed until it's your go again",
    "Empty out your wallet/purse and show everyone what's inside",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Whisper a secret to the person on your left",
    "Say two honest things about everyone else in the group",
    "Tell the saddest story you know",
    "Hold your drink with two hands for the rest of the evening",
    "Put on make-up without a mirror and leave it like that for the rest of the game",
    "Neck the drink (responsibly) of the person on your right",
    "Say yes to everything for the next 1 minute",
    "Show your favourite picture of yourself",
    "Post a TikTok draft",
    "Make a rap about your favourite book",
    "Do 50 push ups",
    "Reveal what you think everyone in the group will be up to in five years time",
    "Give everyone in the room a backhanded compliment",
    "Let the group style your hair and leave it that way for the entire game",
    "Only talk in whispers for the next 10 minutes",
    "Say a secret about someone in the room but not reveal their name",
    "Eat five spoonfuls of a condiment of your choice",
    "Pretend to be a food item of your choice",
    "Eat a raw piece of garlic",
    "Give a lap dance to someone of your choice",
    "Repeat everything the person on your right is saying until it's your turn again",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Show your orgasm face",
    "Seductively eat a banana",
    "Do your best sexy crawl",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Let another person in the group touch up your makeup",
    "Talk in an American accent for the rest of the evening",
    "Do your best celebrity impression",
    "Play air guitar for 2 minutes straight",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Belt out the chorus of a cheesy ballad at full volume",
    "Let someone else tickle you and try not to laugh",
    "Down your drink (responsibly)",
    "Try and make yourself cry in front of the group",
    "Give a celebrity lookalike for every person in the room",
    "Attempt to impersonate everyone in the room",
    "Fill your mouth with drink and gargle your answer to the next Truth",
    "Make another player jump in the next 10 minutes",
    "Attempt the first TikTok dance on your for you page",
    "Try not to laugh for the next 10 minutes",
    "For the next 10 minutes, every time someone asks you something, respond with a bark",
    "Call the first person in your phonebook and howl like a wolf",
    "Let the person next to you wax you wherever they want",
    "Download the Wetherspoons app and order a random food item to someone's table",
    "Do the cinnamon challenge",
    "Run out of the house and shout 'I'm not like a regular mom, I'm a cool mom!'",
    "Rap the whole of WAP while dancing seductively",
    "Go outside and sing 'Football's Coming Home' at full volume",
    "Narrate the game like a newsreader for the next round",
    "While pretending to drink a martini, give a Kris Jenner-esque speech to all the players in the room (FYI, they're loooooooong)",
    "Take a group picture (ala 2000s S Club 7 vibes) and announce you're starting a new band called 'The Glen Coco's'",
    "Allow someone else in the group to blindfold you and feed you one item out of the fridge",
    "Let the group decide your outfit for the night",
    "Do a shot of vinegar",
    "Show a picture of your most cringe outfit",
    "Read out the last five things on your search history",
    "Let another player draw a tattoo on your foot in permanent marker",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "Try and get all the toes on one foot in your mouth",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Peel a banana with your toes",
    "Say everything in a whisper for the next 10 minutes",
    "Smell another player's armpit",
    "Put as many snacks into your mouth at once as you can",
    "Put your clothing on backwards for the rest of the evening",
    "Put on as many layers as possible in 60 seconds",
    "Smile as widely as you can and hold it for two minutes",
    "Sit on the floor for the rest of the evening",
    "Eat a raw egg",
    "Sit in the corner of the room without speaking to anyone for the next 10 minutes",
    "Let someone order something random on your Amazon account (£10 or under)",
    "Eat a spoonful of black pepper",
    "Eat a whole block of cheese",
    "Walk around the room like a chicken for one minute",
    "Eat a raw onion like an apple",
    "Do your best Shrek impression",
    "Serenade the person to your left",
    "Share with the group your worst vomit story",
    "Swap shoes with the person sitting to your right (if they’re comfortable with this)",
    "Read out the last dirty text you sent",
    "Say something dirty to the person on your left",
    "Remove four items of clothing",
    "Send a sext to the last person in your phonebook",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Scroll through your phone book until someone says stop. You either have to call or delete that person.",
    "Tell the group two truths and a lie, and they have to guess which one the lie is",
    "Reply to the first five Instagram Stories on your timeline",
    "Share the first celebrity on your timeline's Instagram to your Story",
    "Give a personalised insult to everyone in the room",
    "Do a Facebook Live and say everything your friends tell you to",
    "Update your relationship status to 'engaged' on Facebook",
    "Call a person in the room's dad and tell him you think he's sexy",
    "Post a random baby scan on Facebook",
    "Update your Facebook status to tell your friends you're moving to Australia",
    "Comment a fire emoji on the first five pictures on your Instagram feed",
    "Add a family member to your girls' group chat and start a weird conversation",
    "Perform a seductive dance for the whole group",
    "Add all of your exes into a group chat and ask what went wrong",
    "Write your name on the floor using your tongue",
    "Do an imitation of your favourite TikToker",
    "Share a picture of your current crush with the rest of the group",
  ],
};
